#
# Makefile for pipeline_simulator
#

# if you want to use debugger, add -g to CFLAGS and LDFLAGS

pipeline: main.cpp pipeline.h 
	g++ -o pipeline main.cpp pipeline.h


clean:
	rm -rf *.o *.bin *.rpt *.exe *.out
